# code from docker hub: https://hub.docker.com/_/mongo

services:

  mongo:
    image: mongo
    restart: unless-stop
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express
    restart: unless-stop
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge